### ISSUE TITLE
Pre trained weights

### ISSUE THREAD

**Issue by no-1ne** [sercant/mobile-segmentation#1]
Folks awesome job with being able to do real time segmentation with shufflenet 2. 

Do you mind sharing the pretrained weights

**Comment by sercant** [comment]
Thanks, @startupgurukul. Pretrained weights are coming soon.

**Comment by sercant** [comment]
Checkpoints for `cityscapes` data set is available under the [release section](https://github.com/sercant/mobile-segmentation/releases) now.

**Comment by no-1ne** [comment]
Awesome thanks
