### ISSUE TITLE
Training my own data

### ISSUE THREAD

**Issue by hanseun** [sercant/mobile-segmentation#11]
Hi Author!

I'm trying to train using my own data.
I made tfdata and tried to excute train.py. 
But I can't define "tf_initial_checkpoint".
Could you please help me out?

**Comment by sercant** [comment]
Hello @hanseun,

Can you add the error that you are getting while trying to define `tf_initial_checkpoint`?

The issue might be one of the following:

1. If your class count is different, you haven't set `initialize_last_layer` to `False`.
2. The checkpoint you are trying to restore is using `DPC` and you haven't specified that you want to use `DPC` by setting `dense_prediction_cell_json` parameter or vice versa.

If you send me the error message I can help you better.

**Comment by hanseun** [comment]
thanks!
