### ISSUE TITLE
some thing about the DPC module

### ISSUE THREAD

**Issue by cs-heibao** [sercant/mobile-segmentation#6]
@sercant 
the DPC module, the input is the ShuffleNet V2 stage4 (that means the input channel is 464) and here, the five branches conv's kernel out_channel is 256(as reffered in the paper "Searching for Efficient Multi-Scale Architectures for Dense Image Prediction") of DPC.
While, as for depthwise_conv2d, the out_channel of convs result is in_channel(inputs )* 256(kernel out_channel). So after 5 braches, we use tf.concat, the final result's out_channel is a very big number ?

**Comment by sercant** [comment]
Hello @junjieAI, thank you for your interest. But I couldn't understand your question. Do you mean that the channel output of the DPC is bigger than expected?

**Comment by cs-heibao** [comment]
@sercant 
thanks, recently, I implement the DPC module in tensorflow, and the input's shape of DPC is (45×90×1024),
and as your paper fig.4 (b), from top to down, left to right,the first DWConv(the filters out_channel is 256) final conv result's shape is (45 × 90×(1024×256)) , and the second  DWConv final conv result's shape is (45×90×(1024×256×256)), and the third is also (45×90×(1024×256×256)) as well as the fourth, and the fifth is (45×90×(1024×256×256×256)), and concat result shape is  (45×90×((1024×256) + (1024×256×256)×3 +(1024×256×256×256)).
I don't know whether my understanding is right , thanks

**Comment by sercant** [comment]
Hello @junjieAI,

I am not quite sure how do you get the big numbers like that but here is a visualization of the implementation that was used in our work. I think that would help you see much better. The channel width never goes above 256 in any branch and the final channel width after the concatenation is 1280. Which is then again reduced down to 256. Please don't hesitate to ask any further questions.

![Netron visualization of DPC](https://i.imgur.com/jHMZJ0e.png)

**Comment by cs-heibao** [comment]
@sercant 
wow, it's much more clear to understand, and here some operations hope you give detailed instructions, how is the exactly of Mul and Add as well as the tf.space_to_batch_nd and tf.batch_to_space_nd
for example
```
(block_shape=tf.constant([2,2],tf.int32)
paddings=tf.constant([[2,3],[2,3]],tf.int32))
```
how is the block_shape and paddings

thanks

**Comment by sercant** [comment]
Hello @junjieAI,

I think those operations are a result of a Tensorflow optimization before or during the model freezing to achieve atrous (dilated) convolutions. You shouldn't use those low-level functions and instead look for the higher level operations. I suggest you read the code in `core/dense_prediction_cell.py` and especially examine the code segment here:

https://github.com/sercant/mobile-segmentation/blob/9cac777740fd55ef67099611aee720f44774264c/core/dense_prediction_cell.py#L218-L227

and follow it according to `dense_prediction_cell_branch5_top1_cityscapes.json`:

```json
[
  {
    "kernel": 3,
    "rate": [
      1,
      6
    ],
    "op": "conv",
    "input": -1
  },
  {
    "kernel": 3,
    "rate": [
      18,
      15
    ],
    "op": "conv",
    "input": 0
  },
  {
    "kernel": 3,
    "rate": [
      6,
      3
    ],
    "op": "conv",
    "input": 1
  },
  {
    "kernel": 3,
    "rate": [
      1,
      1
    ],
    "op": "conv",
    "input": 0
  },
  {
    "kernel": 3,
    "rate": [
      6,
      21
    ],
    "op": "conv",
    "input": 0
  }
]
```

If you follow the code (or debug it step by step) you can get a much better understanding of the functions that are used in the process.

**Comment by cs-heibao** [comment]
@sercant 
![Screenshot from 2019-07-09 14-57-25](https://user-images.githubusercontent.com/33689425/60871243-ef7eba80-a264-11e9-9296-3903226794e9.png)
as mentioned in the picture, here 
`(block_shape=tf.constant([?,?],tf.int32)
paddings=tf.constant([[?,?],[?,?]],tf.int32))
`
what should I fill in the above?
thanks

**Comment by sercant** [comment]
@junjieAI like I said in the previous comment, those are generated by Tensorflow. Please read my comment carefully.

**Comment by cs-heibao** [comment]
extremely grateful for you!

**Comment by sercant** [comment]
The operations used in the branches only consist of `slim.separable_conv2d` and point-wise `slim.conv2d`.
