### ISSUE TITLE
COCO2017

### ISSUE THREAD

**Issue by lilingge** [sercant/mobile-segmentation#8]
Hi ,author.
I really want to get the images like the "the folder of getfine in cityscapes data set".such as 
'cityscapes/gtFine/train/aachen/aachen_000000_000019_gtFine_labelIds.png' and corresponding to the image such as 'cityscapes/leftImg8bit/train/aachen/aachen_000000_000019_leftImg8bit.png'.
I can make txt files to input data.

**Comment by lilingge** [comment]
And when I run the build_coco_data.py without any operations.
error:
bytes_list=tf.train.BytesList(value=[norm2bytes(values)]))
TypeError: u'./COCO//val2017/000000397133.jpg' has type unicode, but expected one of: bytes

**Comment by sercant** [comment]
Dear @lilingge,

This error is a python related error. Unicode errors usually happen in python 2.x versions. I suggest you search for this error online or maybe create a stackoverflow question as it is not related to this repository.
